/**
 * SEO helper — fetches seo_title, seo_description, og_image from WordPress
 * via the /wp-json/pl/v1/seo?page_id={id} endpoint (pl-seo-rest plugin).
 *
 * Fields are written by the pl-seo-save plugin (POST /wp-json/pl/v1/save-seo)
 * and auto-generated by the pl-seo-ai plugin on every page save.
 */

const WP_URL = process.env.NEXT_PUBLIC_WC_URL ?? ''
const REVALIDATE = 3600

// Maps WordPress page slug → page ID
const SLUG_TO_ID: Record<string, number> = {
  'home':      21,
  'about':     30,
  'contact':   32,
  'guide':     34,
  'shop-hero': 36,
}

export interface PageSEO {
  title: string
  description: string
  ogImage?: string
  noIndex?: boolean
}

/**
 * Fetch SEO fields for a WordPress page by slug.
 * Falls back to `fallback` if fields are empty or the request fails.
 */
export async function getPageSEO(slug: string, fallback: PageSEO): Promise<PageSEO> {
  const pageId = SLUG_TO_ID[slug]
  if (!pageId) return fallback

  try {
    const res = await fetch(
      `${WP_URL}/wp-json/pl/v1/seo?page_id=${pageId}`,
      { next: { revalidate: REVALIDATE } },
    )
    if (!res.ok) return fallback
    const data = await res.json() as { seo_title?: string; seo_description?: string; og_image?: string }

    const title = data.seo_title?.trim() || fallback.title
    const description = data.seo_description?.trim() || fallback.description
    const ogImage = data.og_image?.startsWith('http') ? data.og_image : fallback.ogImage

    return { title, description, ogImage }
  } catch {
    return fallback
  }
}
